# Generated by Django 3.1.6 on 2021-02-14 16:23

import api.authentication.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('f23d52a2-b672-4aa5-beed-3871d994bfd9'), editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.authentication.models.UserManager()),
            ],
        ),
    ]
