# Generated by Django 3.1.6 on 2021-02-14 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geouser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de48d2d5-4e61-44eb-aa31-56fa0b5bc60c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
