# Generated by Django 3.1.6 on 2021-02-14 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210214_1623'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='geouser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='geouser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('01bd0154-0cd8-4f8d-bf7d-10466212812c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
