# Generated by Django 3.1.6 on 2021-02-15 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210214_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geouser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80144b95-3c8d-42d2-a9fe-fc52957be9ff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
