# Generated by Django 3.1.6 on 2021-02-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_requesthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesthistory',
            name='n',
            field=models.PositiveIntegerField(),
        ),
    ]
